config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes, except: :delete do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users,      only: [:edit, :update, :show]
  resources :tags, only: [:index, :show]

  scope module: :prototypes do
    resources :popular, only: :index
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
  validates :text, :user_id, :prototype_id, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :content, ImageUploader
  enum content_type: {main: 0, sub: 1}
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
  def like_user(user_id)
    like.find_by(user_id: user_id)
  end
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  scope :popular, -> { order("likes_count DESC") }

  belongs_to :user
  has_many   :images, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc { |attributes| attributes[:content].blank? }
  validates :images, :title, :concept, :catch_copy, presence: true
  acts_as_taggable_on :tags
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email,:name, :group, :profile, :works, presence: true
  mount_uploader :image, ImageUploader
  has_many :prototypes
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger
  class PermissionDenied < StandardError; end

  rescue_from PermissionDenied do
    redirect_to :root, alert: "You don't have permittion."
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :works, :group, :image])
  end

  def comfirm_user(resource)
    if resource.class.name == "User"
      raise PermissionDenied if resource != current_user
    else
      raise PermissionDenied if resource.user != current_user
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :user_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < PrototypesController

  def index
    @prototypes = Prototype.includes(:user).popular.page(params[:page])
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :prototype_set, only: [:edit, :update, :show, :destroy]
  before_action -> {comfirm_user(@prototype)}, only: [:edit, :update, :destroy]
  def index
    @prototypes = Prototype.includes(:user).order("created_at DESC").page(params[:page])
  end
  def new
    @prototype = Prototype.new
    @prototype.images.build
  end
  def create
    @prototype = current_user.prototypes.new(proto_params)
    if @prototype.save
      redirect_to root_path, notice: 'You succeeded in posting'
    else
      flash[:alert] = "You can't post it"
      render action: :new
    end
  end
  def show
    @comment = Comment.new
    @like = Like.find_by(prototype_id: @prototype.id)
  end
  def edit
  end
  def update
    if @prototype.update(proto_params)
      redirect_to root_path, notice: 'You suceeded in updating'
    else
      flash[:alert] = "You can't edit it"
      render action: :edit
    end
  end
  def destroy
    if @prototype.destroy
      redirect_to root_path, notice: 'You succeeded in deleting'
    else
      flash[:alert] = "You can't delete it"
      render action: :index
    end
  end
  private
  def proto_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      images_attributes: [:id, :content,:content_type]
    ).merge(tag_list: params[:prototype][:tag_list])
  end

  def prototype_set
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.all.uniq
  end

  def show
    tag = ActsAsTaggableOn::Tag.where(name: params[:id])
    @prototypes = Prototype.tagged_with(tag.name)
    render template: "prototypes/index"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action -> {comfirm_user(@user)}, only: [:edit, :update]
  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "You succeeded to edit your profile"
    else
      render edit_user_path(@user), alert: "You can't edit"
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:name, :works, :profile, :group, :image)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$("#comment_text").val("")
$("#comments_list").html("<%= j(render partial: 'prototypes/comment', collection: @prototype.comments) %>");

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  - key == "notice" ? key = "info" : key = "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle{type: "button", data: {toggle: "collapse",  data: {target: ".navbar-responsive-collapse"}}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{aria: {expanded: "false"}, data: {toggle: "dropdown"}, href: "#", role: "button"}
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "My Page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path
        - else
          %ul.nav.navbar-nav.navbar-right
            %li
              .btn.btn-primary.navbar-btn
                = link_to "Get started", new_user_session_path

app/views/layouts/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path(like, prototype_id: prototype.id), method: :delete, id: "like-button", class: "btn-default decrement-button", remote: true do
      = image_tag("icon_heart_red.svg")
      %span
        Like
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), id: "like-button", class: "btn-default increment-button", remote: true do
      = image_tag("icon_heart.svg")
      %span
        Like
        = prototype.likes_count
- else
  = button_to prototype_likes_path(prototype), id: "like-button", class: "btn-default increment-button", remote: true do
    = image_tag("icon_heart.svg")
    %span
      Like
      = prototype.likes_count

app/views/layouts/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    - if user_signed_in?
      - if current_user.id == proto.user_id
        .dropdown.drop_menu_location
          %button.btn.btn-default.dropdown-toggle{ type: "button", data: {toggle: "dropdown"}, area: {expanded: false}}
            Action
          %ul.dropdown-menu{ aria: {labelledby: "dropdownMenu1"}}
            %li
              = link_to 'Delete', prototype_path(proto), method: :delete
            %li
              = link_to 'Edit', edit_prototype_path(proto)
    = link_to prototype_path(proto) do
      = image_tag(proto.images.main.first.content)
    .caption
      %h3= proto.title
      .proto-meta
        .proto-user
          = link_to "by #{proto.user.name}", user_path(proto.user)
        .proto-posted
          = proto.created_at.to_s(:date)
      %ul.proto-tag-list.list-inline
        - proto.tag_list.each do |tag|
          = link_to tag, tag_path(tag), class: "btn btn-default"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http: {equiv: "Content-Type"}}
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true}}
    = javascript_include_tag 'application', data: { turbolinks: { track: true}}
    = csrf_meta_tags
  %body
    .wrapper
      = render "layouts/header"
      = render "layouts/flash"
      = yield
      = render "layouts/footer"

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'prototypes/like', locals: { prototype: @prototype, likes: @likes, like: @like }) %>");

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'prototypes/like', locals: { prototype: @prototype, likes: @likes, like: @like }) %>");

app/views/prototypes/_comment.html.haml
%li.media
  .media-left
    = link_to user_path(comment.user) do
      - if comment.user.image.present?
        = image_tag(comment.user.image, alt: "64x64", data: { holder: { rendered: true }}, data: { src: "holder.js/64x64"}, style: "width: 64px; height: 64px")
      - else
        = image_tag("default.png", alt: "64x64", data: { holder: { rendered: true }}, data: { src: "holder.js/64x64"}, style: "width: 64px; height: 64px")
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{href: "#top-aligned-media"}
        %span.anchorjs-icon
    %p= comment.text

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path(like, prototype_id: prototype.id), method: :delete, id: "like-button", class: "btn-default decrement-button", remote: true do
      = image_tag("icon_heart_red.svg")
      %span
        Like
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), id: "like-button", class: "btn-default increment-button", remote: true do
      = image_tag("icon_heart.svg")
      %span
        Like
        = prototype.likes_count
- else
  = button_to new_user_session_path, class: "btn-default" do
    = image_tag("icon_heart.svg")
    %span
      Like
      = prototype.likes_count

app/views/prototypes/edit.html.haml
.container.proto-new
  .col-md-8.col-md-offset-2
    = form_for @prototype do |f|
      - if @prototype.errors.any?
        .explain_errors
          %h2= "#{@prototype.errors.count} errors"
          %ul
          - @prototype.errors.full_messages.each do |error|
            %li #{error}
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", class:"proto-new-title", value: "#{@prototype.title}"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :images, @prototype.images.main.first do |img|
              = img.file_field :content, class: "js-preview", data: { preview: "#js-image0" }
              = image_tag (@prototype.images.main.first.content), id: "js-image0", class: "js-pre-images"
              = img.hidden_field :content_type, value: :main
        .col-md-12
          %ul.proto-sub-list.list-group
            - @prototype.images.sub.each.with_index(1) do |sub, i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images, sub do |img|
                    = img.file_field :content, class: "js-preview", data: { preview: "#js-image#{i}" }
                    = image_tag (sub.content), id: "js-image#{i}", class: "js-pre-images"
                    = img.hidden_field :content_type, value: :sub
            %li.list-group-item.col-md-4
              .image-upload.hidden
                = f.fields_for :images do |img|
                  = img.file_field :content, class: "js-preview", data: { preview: "#js-image3" }
                  = image_tag (""), id: "js-image3", class: "js-pre-images"
                  = img.hidden_field :content_type, value: :sub
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy", value: "#{@prototype.catch_copy}"
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept", value: "#{@prototype.concept}"
        .col-md-12
          %h4 Tag List
          .row
            - @prototype.tag_list.each do |tag|
              .col-md-3
                = text_field_tag "prototype[tag_list][]", "#{tag}", placeholder: "Tag"
      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{class: "#{'active' if current_page?(popular_index_path)}"}
          = link_to "Popular PROTO", popular_index_path
        %li{class: "#{'active' if current_page?(root_path)}"}
          = link_to "Newest PROTO", root_path
      = button_to "View Tags", tags_path, method: :get, class: "btn-default"
.container.proto-list
  .row
    - @prototypes.each do |proto|
      = render partial: 'layouts/prototype', locals: { proto: proto }
.text-center
  = paginate @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  .col-md-8.col-md-offset-2
    = form_for @prototype do |f|
      - if @prototype.errors.any?
        .explain_errors
          %h2= "#{@prototype.errors.count} errors"
          %ul
          - @prototype.errors.full_messages.each do |error|
            %li #{error}
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", class:"proto-new-title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :images do |img|
              = img.file_field :content, class: "js-preview", data: { preview: "#js-image0" }
              = image_tag (""), id: "js-image0", class: "js-pre-images"
              = img.hidden_field :content_type, value: :main
        .col-md-12
          %ul.proto-sub-list.list-group
            - 2.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images do |img|
                    = img.file_field :content, class: "js-preview", data: { preview: "#js-image#{i + 1}" }
                    = image_tag (""), id: "js-image#{i + 1}", class: "js-pre-images"
                    = img.hidden_field :content_type, value: :sub
            %li.list-group-item.col-md-4
              .image-upload.hidden
                = f.fields_for :images do |img|
                  = img.file_field :content, class: "js-preview", data: { preview: "#js-image3" }
                  = image_tag (""), id: "js-image3", class: "js-pre-images"
                  = img.hidden_field :content_type, value: :sub
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do
              .col-md-3
                = text_field_tag 'prototype[tag_list][]', "", placeholder: "Tag"
      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %a{href: "#"}
          = link_to user_path(@prototype.user) do
            %img.media-object{alt: "64x64", data: { holder: {rendered: true}}, data: { src: "holder.js/64x64"}, src: "#{@prototype.user.image}", style: "width: 64px; height: 64px;"}
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by #{@prototype.user.name}", user_path(@prototype.user)
            %span.degree
              = @prototype.user.works
    .col-md-6.clearfix
      #like-buttons
        = render partial: 'like', locals: { prototype: @prototype, likes: @likes, like: @like }
  .row
    .col-md-9
      = image_tag(@prototype.images.main.first.content, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.images.sub.each do |sub_image|
          %li.list-group-item
            = image_tag(sub_image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num= @prototype.comments.length
    %ul.col-md-8#comments_list
      = render partial: 'prototypes/comment', collection: @prototype.comments
    - if user_signed_in?
      = form_for [@prototype, @comment], class: 'form-inline', remote: true do |f|
        - if @comment.errors.any?
          .explain_errors
            %h2= "#{@comment.errors.count} errors"
            %ul
            - @comment.errors.full_messages.each do |error|
              %li #{error}
        %h4.col-md-12 Write a comment
        .row
          .form-group.col-md-7
            = f.text_area :text, class: 'form-control', rows: '3', placeholder: 'Your comments'
            = f.hidden_field :user_id, value: current_user.id
          .form-group.col-md-5
            = f.submit 'Comment', class:'btn btn-primary'

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        - @tags.each do |tag|
          %li.col-md-2
            = link_to tag.name ,tag_path(tag), class: "btn btn-default"

app/views/users/edit.html.haml
.container.user-new
  = form_for(@user) do |f|
    - if @user.errors.any?
      .explain_errors
        %h2= "#{@user.errors.count} errors"
        %ul
        - @user.errors.full_messages.each do |error|
          %li #{error}
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Username", value: "#{@user.name}"
            .user-image.col-md-2{style: 'background-image: url(<%= @user.image %>);'}
              %button.btn.btn-primary Change image
              = f.file_field :image
          = f.email_field :email, placeholder: "E-Mail", value: " #{@user.email}", class: "user-email"
          = f.password_field :password, placeholder: "Password", class: "user-password"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :group, placeholder: "Member", value: "#{@user.group}"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: 30, rows: 4, placeholder: "Profile", value: "#{@user.profile}"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :works, cols: 30, rows: 4, placeholder: "Works", value: "#{@user.works}"
    .row.text-center.user-btn
      = f.submit "SAVE", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to user_path(@user) do
          %img.media-object{alt: "64x64", data: { holder: { rendered: true}}, data: { src: "holder.js/64x64"}, src: "#{@user.image}", style: "width: 64px; height: 64px;"}
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            = @user.prototypes.length
            %i Projects
        .proto-user
          %span.degree= @user.group
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Works
            %p= @user.works
.container.proto-list
  .row
    - @user.prototypes.each do |proto|
      = render partial: 'layouts/prototype', locals: { proto: proto}
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label": "Previous", href: "#"}
        %span{"aria-hidden": "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »